# Generated by Django 5.1.2 on 2024-10-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('fullName', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
